name: Release Build

on:
  workflow_dispatch:

permissions: write-all

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short
  HUSKY: 0

jobs:
  release:
    name: Release Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.91.0'
          targets: ${{ matrix.target }}

      - name: Install x86 OpenSSL
        if: matrix.target == 'x86_64-apple-darwin'
        run: |
          arch -x86_64 brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Pnpm install and check
        run: |
          pnpm i
          pnpm run prebuild ${{ matrix.target }}

      - name: Tauri build
        uses: tauri-apps/tauri-action@v0.5
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseName: 'Clash Verge Mac Build'
          releaseBody: 'macOS build without code signing.'
          releaseDraft: true
          prerelease: false
          tauriScript: pnpm
          args: --target ${{ matrix.target }}
          includeUpdaterJson: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: clash-verge-mac-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/bundle/dmg/*.dmg
